#!/usr/bin/env ruby

red = "\e[0;31m"
green= "\e[0;32m"
cyan = "\e[0;36m"

boldred = "\e[4;31m"
boldgreen= "\e[4;32m"
boldcyan = "\e[4;36m"

noformat = "\e[0m"
nocolor = "\e[39m"

repos = {}
`git submodule foreach git branch`.scan(/Entering '([-\w]+)'[^*]+\* ([-\w]+)/m).each  do |repo, branch|
  repos[repo] = { branch: branch }
end

longest_repo_name = 0
repos.each{|name, repo| longest_repo_name = name.length if name.length > longest_repo_name }

`git status`.each_line do |line|
  if line.match(/modified:[ ]+([\w-]+) (\([^)]+\))?/)
    repos[$1][:changes] = true
    repos[$1][:change_type] = $2
  end
end

repos.each do |name, repo|
  if repo[:changes]
    puts "#{boldcyan}#{name.ljust(longest_repo_name)} #{nocolor}@ #{boldred}#{repo[:branch]}#{nocolor} #{boldgreen}#{repo[:change_type]}#{noformat}"
    system "cd #{name} && git status --short && cd .."
    puts
    repos.delete(name)
  end
end

repos.each do |name, repo|
  puts "#{cyan}#{name.ljust(longest_repo_name)} #{nocolor}@ #{red}#{repo[:branch]}#{noformat} (clean)"
end
